apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato

          image: charan027/test:1.0
          imagePullPolicy: Always # Ensures it always pulls the new build
          ports:
            - containerPort: 80
