apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  type: NodePort
  ports:
    - port: 80
      #  Target the container's port 80
      targetPort: 80
      # We can keep this. We'll access the app on <Node_IP>:30001
      nodePort: 30001
  selector:
    app: zomato
